discord.token=${DISCORD_TOKEN}
groq.api.key=${GROQ_API_KEY}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
moderation.log-channel-id=${MODERATION_LOG_CHANNEL_ID}
spring.jpa.hibernate.ddl-auto=update